import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Helper function to extract slugs from content.ts
function extractSlugs(content, arrayName) {
  const arrayStart = content.indexOf(`export const ${arrayName}`);
  if (arrayStart === -1) return [];
  
  let arrayEnd = content.indexOf('export const', arrayStart + 10);
  if (arrayEnd === -1) arrayEnd = content.length;
  
  const arrayStr = content.slice(arrayStart, arrayEnd);
  const slugs = [];
  // Match `slug: 'value'`
  const regex = /slug:\s*'([^']+)'/g;
  let match;
  while ((match = regex.exec(arrayStr)) !== null) {
      slugs.push(match[1]);
  }
  return slugs;
}

// Format slug into a readable title
function formatSlugToTitle(slug) {
  return slug.split('-').map(word => word.charAt(0).toUpperCase() + word.slice(1)).join(' ');
}

async function generateRoutes() {
  console.log('Generating static HTML files for all routes...');
  
  const contentMapPath = path.resolve(__dirname, '../src/data/content.ts');
  const content = fs.readFileSync(contentMapPath, 'utf-8');
  
  const servicesSlugs = extractSlugs(content, 'services');
  const caseStudySlugs = extractSlugs(content, 'caseStudies');
  const blogPostSlugs = extractSlugs(content, 'blogPosts');

  const routes = [
    { 
      path: '/', 
      title: 'FutureSource | Web Design & Web Development Marketing Agency Montreal',
      description: 'Experienced Web Development & Digital Marketing Agency in Montreal. Scaling brands using technical SEO, Paid Ads, CRO, and Account-Based Marketing (ABM).'
    },
    { 
      path: '/services', 
      title: 'FutureSource | Web Design & Web Development Marketing Agency Montreal',
      description: 'Experienced Web Development & Digital Marketing Agency in Montreal. Scaling brands using technical SEO, Paid Ads, CRO, and Account-Based Marketing (ABM).'
    },
    { path: '/work', title: 'Work | FutureSource' },
    { 
      path: '/about', 
      title: 'FutureSource | Web Design & Web Development Marketing Agency Montreal',
      description: 'Experienced Web Development & Digital Marketing Agency in Montreal. Scaling brands using technical SEO, Paid Ads, CRO, and Account-Based Marketing (ABM).'
    },
    { path: '/process', title: 'Our Process | FutureSource' },
    { path: '/pricing', title: 'Pricing | FutureSource' },
    { path: '/insights', title: 'Insights | FutureSource' },
    { path: '/contact', title: 'Contact | FutureSource' },
    { path: '/book-a-call', title: 'Book a Call | FutureSource' },
    { path: '/privacy', title: 'Privacy Policy | FutureSource' },
    { path: '/terms', title: 'Terms of Service | FutureSource' },
    { path: '/cookies', title: 'Cookie Policy | FutureSource' }
  ];

  servicesSlugs.forEach(slug => {
    let title = `${formatSlugToTitle(slug)} | Services | FutureSource`;
    let description = `FutureSource ${formatSlugToTitle(slug)} page. Performance marketing for ambitious brands.`;
    
    // Custom meta tags for web-design
    if (slug === 'web-design') {
      title = 'FutureSource | Custom Web Design & Expert Web Development Montreal';
      description = 'Creative Montreal agency for Custom Web Design & Development. We build responsive, SEO-friendly websites that scale your brand and drive digital performance.';
    }
    
    routes.push({ 
      path: `/services/${slug}`, 
      title: title,
      description: description
    });
  });

  caseStudySlugs.forEach(slug => {
    routes.push({ path: `/work/${slug}`, title: `Case Study: ${formatSlugToTitle(slug)} | FutureSource` });
  });

  blogPostSlugs.forEach(slug => {
    routes.push({ path: `/insights/${slug}`, title: `${formatSlugToTitle(slug)} | FutureSource Insights` });
  });

  const distDir = path.resolve(__dirname, '../dist');
  const templatePath = path.join(distDir, 'index.html');

  if (!fs.existsSync(templatePath)) {
    console.error('Error: dist/index.html not found. Vite build failed or hasn\'t run.');
    process.exit(1);
  }

  const template = fs.readFileSync(templatePath, 'utf-8');

  routes.forEach(route => {
    if (route.path === '/') return; // Root HTML is already generated by Vite
    
    // Create physical directory for route (e.g., dist/about)
    const routeDir = path.join(distDir, route.path);
    if (!fs.existsSync(routeDir)) {
      fs.mkdirSync(routeDir, { recursive: true });
    }
    
    // Inject specific Title and Description tags for SEO
    let customHtml = template.replace(
      /<title>.*?<\/title>/i,
      `<title>${route.title}</title>`
    );
    
    const metaDescription = route.description || `FutureSource ${route.title.replace(/\|/g, '-')} page. Performance marketing for ambitious brands.`;
    
    customHtml = customHtml.replace(
      /<meta name="description" content="[^"]*"/i,
      `<meta name="description" content="${metaDescription}"`
    );

    // Save the customized HTML into the new path (e.g., dist/about/index.html)
    fs.writeFileSync(path.join(routeDir, 'index.html'), customHtml);
    console.log(`✓ Generated static page: ${route.path}`);
  });
  
  console.log(`\nSuccessfully generated ${routes.length - 1} physical HTML pages for SEO!`);
}

generateRoutes().catch(console.error);
